name: Build TikTok Bot for macOS and Windows

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [main]  # Adjust as needed

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build for Windows
        run: npm run make:all

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: TiktokReplyBot-windows
          path: out/make/**/*.exe

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build for macOS
        run: npm run make-mac:all

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: TiktokReplyBot-mac
          path: out/make/**/*.zip
